# Generated by Django 3.2 on 2021-05-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='متن نمایشی', max_length=100, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='product_sub_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='متن نمایشی', max_length=100, null=True, verbose_name='متن')),
                ('group', models.ForeignKey(blank=True, help_text='درصورت داشتن سر گروه ، وارد شود ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_group', to='product.product_group', verbose_name='سر گروه')),
            ],
            options={
                'verbose_name': 'زیر گروه',
                'verbose_name_plural': 'زیر گروه ها',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کالا')),
                ('description_one', models.CharField(blank=True, help_text='کمتر از ۱۰۰ کلمه', max_length=100, null=True, verbose_name='توضیحات')),
                ('description_two', models.TextField(blank=True, null=True, verbose_name='توضیحات کامل')),
                ('cost', models.IntegerField(verbose_name='قیمت')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='عکس')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_group', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
        ),
    ]
