# Generated by Django 3.2 on 2021-05-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='متن نمایشی', max_length=100, null=True, verbose_name='متن')),
                ('group', models.ForeignKey(blank=True, help_text='درصورت داشتن سر گروه ، وارد شود ', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_group', verbose_name='سر گروه')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_group', verbose_name='گروه'),
        ),
    ]
