# Generated by Django 3.2 on 2021-05-21 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_two',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف'),
        ),
        migrations.CreateModel(
            name='Price_to_weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('weight_type', models.CharField(blank=True, choices=[('1', 'گرم')], max_length=100, null=True, verbose_name='نوع وزن')),
                ('size', models.IntegerField(verbose_name='اندازه')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='کالا')),
            ],
        ),
    ]
