# Generated by Django 3.2 on 2021-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_packs_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='اندازه'),
        ),
    ]
