# Generated by Django 3.2 on 2021-05-21 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210521_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_to_weight',
            options={'verbose_name': 'معیار', 'verbose_name_plural': 'معیار ها'},
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='تخفیف'),
        ),
    ]
