# Generated by Django 3.2 on 2021-05-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_show_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_group',
            name='group',
            field=models.ForeignKey(blank=True, help_text='درصورت داشتن سر گروه ، وارد شود ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_group', to='product.product_group', verbose_name='سر گروه'),
        ),
    ]
