# Generated by Django 3.2 on 2021-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_group_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_group',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
