# Generated by Django 3.2 on 2021-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210521_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('1', 'پیشنهاد'), ('2', 'انتقاد یا شکایت'), ('3', 'مدیریت'), ('4', 'حسابداری'), ('5', 'سایر موضوعات')], max_length=100, null=True, verbose_name='عنوان')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='packs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='packs/icons/', verbose_name='ایکون')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('weight', models.IntegerField(verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'بسته ها',
                'verbose_name_plural': 'بسته',
            },
        ),
    ]
