# Generated by Django 3.2 on 2021-06-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_group_open'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
