# Generated by Django 3.2 on 2021-06-13 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_1', models.CharField(blank=True, max_length=100, null=True)),
                ('number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('number_3', models.CharField(blank=True, max_length=100, null=True)),
                ('number_4', models.CharField(blank=True, max_length=100, null=True)),
                ('number_5', models.CharField(blank=True, max_length=100, null=True)),
                ('number_6', models.CharField(blank=True, max_length=100, null=True)),
                ('number_7', models.CharField(blank=True, max_length=100, null=True)),
                ('number_8', models.CharField(blank=True, max_length=100, null=True)),
                ('number_9', models.CharField(blank=True, max_length=100, null=True)),
                ('number_10', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='packs',
            options={'verbose_name': 'بسته', 'verbose_name_plural': 'بسته ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.properties', verbose_name='خواص'),
        ),
    ]
