# Generated by Django 3.2 on 2021-05-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pack',
        ),
        migrations.AddField(
            model_name='packs',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='کالا'),
            preserve_default=False,
        ),
    ]
