# Generated by Django 3.2 on 2021-05-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210522_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_to_weight',
            options={'verbose_name': 'قیمت', 'verbose_name_plural': 'قیمت ها'},
        ),
        migrations.RemoveField(
            model_name='packs',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='packs',
            name='product',
        ),
        migrations.RemoveField(
            model_name='price_to_weight',
            name='size',
        ),
        migrations.RemoveField(
            model_name='price_to_weight',
            name='weight_type',
        ),
        migrations.AddField(
            model_name='price_to_weight',
            name='pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.packs', verbose_name='بسته'),
            preserve_default=False,
        ),
    ]
