# Generated by Django 3.2 on 2021-06-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210613_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'خاصیت ها', 'verbose_name_plural': 'خواص'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.AddField(
            model_name='properties',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='product.product', verbose_name='خواص'),
            preserve_default=False,
        ),
    ]
