# Generated by Django 3.2 on 2021-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210522_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price_to_weight',
            new_name='product_cost',
        ),
    ]
