# Generated by Django 3.2 on 2021-05-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210522_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product_cost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='product.product', verbose_name='کالا'),
        ),
    ]
