# Generated by Django 3.2 on 2021-06-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_properties_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='number_8',
            new_name='eight',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_5',
            new_name='five',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_4',
            new_name='four',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_9',
            new_name='nine',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_1',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_7',
            new_name='seven',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_6',
            new_name='six',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_10',
            new_name='ten',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_3',
            new_name='three',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='number_2',
            new_name='two',
        ),
    ]
