# Generated by Django 3.2 on 2021-05-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_cost_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cost',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='product.packs', verbose_name='بسته'),
        ),
        migrations.AlterField(
            model_name='product_cost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='product.product', verbose_name='کالا'),
        ),
        migrations.AlterUniqueTogether(
            name='product_cost',
            unique_together=set(),
        ),
    ]
