# Generated by Django 3.2 on 2021-07-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_cost',
            field=models.IntegerField(default=0, verbose_name='قیمت نمایشی'),
        ),
    ]
