# Generated by Django 3.2 on 2021-07-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='product.product'),
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
    ]
