# Generated by Django 3.2 on 2021-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_cost_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_group',
            name='group',
            field=models.ForeignKey(blank=True, help_text='درصورت داشتن سر گروه ، وارد شود ', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_group', verbose_name='سر گروه'),
        ),
    ]
