# Generated by Django 3.2 on 2021-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210709_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cost',
            name='cost',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
