# Generated by Django 3.2 on 2021-05-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_group',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
