# Generated by Django 3.2 on 2021-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_cost_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_group',
            name='open',
        ),
    ]
