# Generated by Django 3.2 on 2021-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_img', models.ImageField(blank=True, null=True, upload_to='login_img/', verbose_name='login')),
                ('register_img', models.ImageField(blank=True, null=True, upload_to='register_img/', verbose_name='register')),
                ('re_password_img', models.ImageField(blank=True, null=True, upload_to='re_password_img/', verbose_name='re password')),
            ],
        ),
    ]
    