# Generated by Django 3.2 on 2021-05-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='national_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='national_code'),
        ),
    ]
