# Generated by Django 3.2 on 2021-05-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date of birth'),
        ),
    ]
