# Generated by Django 3.2 on 2021-05-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_users_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date of birth'),
        ),
    ]
