# Generated by Django 3.2 on 2021-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210609_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='users',
            name='national_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='national_code'),
        ),
    ]
