# Generated by Django 3.2 on 2021-06-13 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210610_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989176666666' or '09176666666'. Up to 15 digits allowed.", regex='((\\+|00)98|0)9\\d{9}')]),
        ),
    ]
