# Generated by Django 3.2 on 2021-06-13 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09176666666'. Up to 11 digits allowed.", regex='((\\+|00)98|0)9\\d{9}')]),
        ),
    ]
