# Generated by Django 3.2 on 2021-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='login_img',
            field=models.ImageField(blank=True, help_text='عکس برای صفحه لاگین ', null=True, upload_to='login_img/', verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='re_password_img',
            field=models.ImageField(blank=True, help_text='عکس برای صفحه فراموشی رمز ', null=True, upload_to='re_password_img/', verbose_name='re password'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='register_img',
            field=models.ImageField(blank=True, help_text='عکس برای صفحه ثبت نام ', null=True, upload_to='register_img/', verbose_name='register'),
        ),
    ]
