# Generated by Django 3.2 on 2021-06-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderrow_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد', 'verbose_name_plural': 'سبد ها'},
        ),
        migrations.AlterModelOptions(
            name='orderrow',
            options={'verbose_name': 'ردیف', 'verbose_name_plural': 'ردیف ها'},
        ),
    ]
