# Generated by Django 3.2 on 2021-07-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrow',
            old_name='pack',
            new_name='product_cost',
        ),
    ]
