# Generated by Django 3.2 on 2021-05-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Private_Site_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سایت')),
                ('title', models.TextField(blank=True, null=True, verbose_name='موضوع سایت')),
                ('description', models.TextField(blank=True, help_text='توضیح کوتاهی درباره ی سایت (همانند شعار سایت)', null=True, verbose_name='توضیحات سایت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس سایت')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفون سایت')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل سایت')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس تلگرام سایت')),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس اینستاگرام سایت')),
                ('whatsapp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس واتس آپ سایت')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات',
            },
        ),
    ]
