# Generated by Django 3.2 on 2021-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_we',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='سر تیتر')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیح کوتاه')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='about_we/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دربارهی ما',
                'verbose_name_plural': 'درباره ی ما',
            },
        ),
    ]
