# Generated by Django 3.2 on 2021-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0002_about_we'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('body', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
    ]
