# Generated by Django 3.2 on 2021-05-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0004_alter_contact_us_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='title',
            field=models.CharField(blank=True, choices=[('پیشنهاد', '1'), ('انتقاد یا شکایت', '2'), ('مدیریت', '3'), ('حسابداری', '4'), ('سایر موضوعات', '5')], default='1', max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
