# Generated by Django 3.2 on 2021-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0007_alter_contact_us_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='title',
            field=models.CharField(blank=True, choices=[('1', 'پیشنهاد'), ('2', 'انتقاد یا شکایت'), ('3', 'مدیریت'), ('4', 'حسابداری'), ('5', 'سایر موضوعات')], max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
