# Generated by Django 3.2 on 2021-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_model', '0008_alter_contact_us_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private_site_information',
            name='address',
        ),
        migrations.RemoveField(
            model_name='private_site_information',
            name='description',
        ),
        migrations.RemoveField(
            model_name='private_site_information',
            name='title',
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='body_1',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='body_2',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='main_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='main_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='motto',
            field=models.TextField(blank=True, null=True, verbose_name='شعار'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='product_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='product_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='product_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='main_site/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='title_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سر تیتر'),
        ),
        migrations.AddField(
            model_name='private_site_information',
            name='title_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سر تیتر'),
        ),
    ]
