# Generated by Django 3.2 on 2021-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_New_Form',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=50, verbose_name='نام حساب')),
                ('type', models.IntegerField(choices=[(1, 'اشخاص'), (2, 'مواد اولیه'), (3, 'محصول')], verbose_name='نوع حساب')),
            ],
        ),
    ]
