# Generated by Django 3.2 on 2021-07-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_Score',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='شماره سند')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accounting_Score_Rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='شرح')),
                ('debit', models.IntegerField(verbose_name='بدهکار')),
                ('credit', models.IntegerField(verbose_name='بستانکار')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts_Form',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=50, verbose_name='نام حساب')),
                ('type', models.IntegerField(choices=[(1, 'اشخاص'), (2, 'مواد اولیه'), (3, 'محصول')], verbose_name='نوع حساب')),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts_New_Form',
        ),
        migrations.AddField(
            model_name='accounting_score_rows',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts_form'),
        ),
        migrations.AddField(
            model_name='accounting_score',
            name='rows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Score', to='accounting.accounting_score_rows'),
        ),
    ]
