# Generated by Django 3.2 on 2021-07-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210711_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting_score_rows',
            name='accounts',
        ),
        migrations.AddField(
            model_name='accounting_score_rows',
            name='accounting_score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_score_rows', to='accounting.accounting_score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounting_score_rows',
            name='accounts_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_score_rows', to='accounting.accounts_form'),
            preserve_default=False,
        ),
    ]
